export const Job_titles = [
  // ========== C-SUITE & EXECUTIVE ==========
  'Chief Executive Officer (CEO)',
  'Chief Operating Officer (COO)',
  'Chief Financial Officer (CFO)',
  'Chief Marketing Officer (CMO)',
  'Chief Technology Officer (CTO)',
  'Chief Information Officer (CIO)',
  'Chief Product Officer (CPO)',
  'Chief Revenue Officer (CRO)',
  'Chief Strategy Officer (CSO)',
  'Chief People Officer (CPO)',
  'Chief Human Resources Officer (CHRO)',
  'Chief Legal Officer (CLO)',
  'Chief Compliance Officer (CCO)',
  'Chief Risk Officer (CRO)',
  'Chief Data Officer (CDO)',
  'Chief Security Officer (CSO)',
  'Chief Innovation Officer',
  'Chief Sustainability Officer',
  'Chief Diversity Officer',
  'Chief Customer Officer',
  'Chief Brand Officer',
  'Chief Growth Officer',
  'Chief Procurement Officer',
  'Chief Supply Chain Officer',
  'Chief Accounting Officer',
  'Chief Audit Executive',
  'Chief Communications Officer',
  'Chief Medical Officer',
  'Chief Nursing Officer',
  'Chief Clinical Officer',
  'Executive Director',
  'Managing Director',
  'Board Member',
  'Chairperson',
  'President',
  'Vice President',
  'Senior Vice President',
  'Executive Vice President',
  'Regional Vice President',
  'Assistant Vice President',

  // ========== SENIOR LEADERSHIP ==========
  'Director',
  'Senior Director',
  'Executive Director',
  'Associate Director',
  'Assistant Director',
  'Head of Department',
  'Head of Operations',
  'Head of Sales',
  'Head of Marketing',
  'Head of Finance',
  'Head of HR',
  'Head of Legal',
  'Head of Product',
  'Head of Engineering',
  'Head of Design',
  'Head of Research',
  'Head of Customer Success',
  'Head of Business Development',
  'Head of Strategy',
  'Head of Communications',
  'Head of Public Relations',
  'Head of Analytics',
  'Head of Quality',
  'Head of Manufacturing',
  'Head of Supply Chain',
  'Head of Logistics',
  'Head of Facilities',
  'Head of Administration',
  'Head of Training',
  'Head of Learning & Development',
  'General Manager',
  'Plant Manager',
  'Factory Manager',
  'Site Leader',
  'Regional Manager',
  'Country Manager',
  'Area Manager',
  'District Manager',
  'Store Manager',

  // ========== FINANCE & ACCOUNTING ==========
  'Finance Director',
  'Finance Manager',
  'Senior Accountant',
  'Accountant',
  'Junior Accountant',
  'Staff Accountant',
  'Certified Public Accountant (CPA)',
  'Chartered Accountant (CA)',
  'Management Accountant',
  'Cost Accountant',
  'Tax Accountant',
  'Tax Specialist',
  'Tax Manager',
  'Tax Director',
  'Auditor',
  'Internal Auditor',
  'External Auditor',
  'Senior Auditor',
  'Audit Manager',
  'Financial Controller',
  'Corporate Controller',
  'Financial Analyst',
  'Senior Financial Analyst',
  'FP&A Analyst',
  'FP&A Manager',
  'Treasurer',
  'Treasury Analyst',
  'Credit Analyst',
  'Risk Analyst',
  'Risk Manager',
  'Compliance Officer',
  'Compliance Analyst',
  'AML Analyst',
  'KYC Analyst',
  'Investment Banker',
  'Investment Analyst',
  'Portfolio Manager',
  'Fund Manager',
  'Hedge Fund Manager',
  'Private Equity Associate',
  'Venture Capital Associate',
  'Wealth Manager',
  'Financial Advisor',
  'Financial Planner',
  'Certified Financial Planner (CFP)',
  'Broker',
  'Trader',
  'Quantitative Analyst',
  'Actuary',
  'Underwriter',
  'Insurance Agent',
  'Claims Adjuster',
  'Claims Manager',
  'Billing Specialist',
  'Payroll Specialist',
  'Payroll Manager',
  'Bookkeeper',
  'Accounts Payable Clerk',
  'Accounts Receivable Clerk',

  // ========== HUMAN RESOURCES ==========
  'HR Director',
  'HR Manager',
  'HR Business Partner',
  'HR Generalist',
  'HR Specialist',
  'HR Coordinator',
  'HR Assistant',
  'Talent Acquisition Director',
  'Talent Acquisition Manager',
  'Recruitment Manager',
  'Senior Recruiter',
  'Recruiter',
  'Technical Recruiter',
  'Corporate Recruiter',
  'Executive Recruiter',
  'Headhunter',
  'Sourcer',
  'Talent Sourcer',
  'Onboarding Specialist',
  'Employee Relations Manager',
  'Employee Relations Specialist',
  'Compensation & Benefits Manager',
  'Compensation Analyst',
  'Benefits Administrator',
  'Payroll Specialist',
  'Training Manager',
  'Learning & Development Manager',
  'Instructional Designer',
  'Trainer',
  'Corporate Trainer',
  'Organizational Development Manager',
  'OD Specialist',
  'HRIS Analyst',
  'HRIS Manager',
  'Diversity & Inclusion Manager',
  'D&I Specialist',
  'Culture Manager',
  'Employee Engagement Specialist',
  'Performance Management Specialist',
  'HR Consultant',
  'Labor Relations Specialist',
  'Union Representative',
  'Workforce Planning Analyst',

  // ========== MARKETING & ADVERTISING ==========
  'Marketing Director',
  'Marketing Manager',
  'Senior Marketing Manager',
  'Brand Manager',
  'Product Marketing Manager',
  'Digital Marketing Manager',
  'Content Marketing Manager',
  'Social Media Manager',
  'Email Marketing Manager',
  'Performance Marketing Manager',
  'Growth Marketing Manager',
  'Field Marketing Manager',
  'Event Marketing Manager',
  'Trade Marketing Manager',
  'Channel Marketing Manager',
  'Marketing Coordinator',
  'Marketing Assistant',
  'Marketing Specialist',
  'Digital Marketing Specialist',
  'SEO Specialist',
  'SEM Specialist',
  'PPC Specialist',
  'Social Media Specialist',
  'Content Creator',
  'Content Writer',
  'Copywriter',
  'Technical Writer',
  'UX Writer',
  'Brand Strategist',
  'Marketing Strategist',
  'Creative Director',
  'Art Director',
  'Graphic Designer',
  'Visual Designer',
  'Web Designer',
  'Multimedia Designer',
  'Motion Graphics Designer',
  'Video Editor',
  'Photographer',
  'Videographer',
  'Media Planner',
  'Media Buyer',
  'Advertising Manager',
  'Account Director (Agency)',
  'Account Manager (Agency)',
  'Account Executive (Agency)',
  'PR Manager',
  'Public Relations Specialist',
  'Communications Manager',
  'Corporate Communications Specialist',
  'Internal Communications Manager',
  'Crisis Communications Specialist',
  'Market Research Analyst',
  'Marketing Analyst',
  'Marketing Data Analyst',
  'Marketing Operations Manager',
  'Marketing Automation Specialist',
  'HubSpot Specialist',
  'Salesforce Marketing Cloud Specialist',

  // ========== SALES & BUSINESS DEVELOPMENT ==========
  'Sales Director',
  'Sales Manager',
  'Senior Sales Manager',
  'Regional Sales Manager',
  'District Sales Manager',
  'Area Sales Manager',
  'National Sales Manager',
  'Global Sales Manager',
  'Key Account Manager',
  'Strategic Account Manager',
  'Major Account Manager',
  'Enterprise Account Manager',
  'Account Executive',
  'Senior Account Executive',
  'Sales Representative',
  'Sales Associate',
  'Inside Sales Representative',
  'Outside Sales Representative',
  'Field Sales Representative',
  'Territory Sales Manager',
  'Business Development Director',
  'Business Development Manager',
  'Business Development Representative',
  'BD Associate',
  'Partnerships Manager',
  'Alliances Manager',
  'Channel Sales Manager',
  'Channel Partner Manager',
  'Reseller Manager',
  'Distributor Manager',
  'Sales Engineer',
  'Solutions Engineer',
  'Pre-sales Consultant',
  'Sales Consultant',
  'Sales Support Specialist',
  'Sales Operations Manager',
  'Sales Operations Analyst',
  'Sales Enablement Manager',
  'Sales Trainer',
  'Sales Coach',
  'Sales Development Representative (SDR)',
  'Business Development Representative (BDR)',
  'Lead Generation Specialist',
  'Cold Caller',
  'Telemarketer',
  'Account Manager',
  'Customer Success Manager',
  'Client Services Manager',
  'Client Relationship Manager',
  'Account Coordinator',
  'Sales Assistant',
  'Retail Sales Associate',
  'Retail Store Manager',
  'Assistant Store Manager',
  'Department Manager',
  'Merchandiser',
  'Wholesale Manager',
  'E-commerce Manager',

  // ========== CUSTOMER SERVICE & SUPPORT ==========
  'Customer Service Director',
  'Customer Service Manager',
  'Customer Service Team Lead',
  'Customer Service Supervisor',
  'Customer Service Representative',
  'Customer Support Specialist',
  'Technical Support Specialist',
  'Help Desk Analyst',
  'Service Desk Analyst',
  'IT Support Specialist',
  'Call Center Manager',
  'Call Center Team Lead',
  'Call Center Agent',
  'Contact Center Agent',
  'Customer Care Representative',
  'Client Support Specialist',
  'Member Services Representative',
  'Patient Services Representative',
  'Guest Services Representative',
  'Front Desk Agent',
  'Receptionist',
  'Concierge',
  'Customer Success Manager',
  'Customer Success Specialist',
  'Onboarding Specialist',
  'Implementation Specialist',
  'Customer Experience Manager',
  'CX Specialist',
  'Voice of Customer Analyst',
  'Customer Feedback Specialist',
  'Quality Assurance Specialist (Customer Service)',
  'Escalation Specialist',
  'Complaints Manager',
  'Customer Advocate',

  // ========== OPERATIONS & LOGISTICS ==========
  'Operations Director',
  'Operations Manager',
  'Senior Operations Manager',
  'Plant Operations Manager',
  'Facility Manager',
  'Supply Chain Director',
  'Supply Chain Manager',
  'Logistics Director',
  'Logistics Manager',
  'Transportation Manager',
  'Fleet Manager',
  'Warehouse Manager',
  'Distribution Manager',
  'Inventory Manager',
  'Inventory Control Specialist',
  'Demand Planner',
  'Supply Planner',
  'Production Planner',
  'Scheduler',
  'Purchasing Manager',
  'Procurement Manager',
  'Procurement Specialist',
  'Buyer',
  'Sourcing Manager',
  'Strategic Sourcing Specialist',
  'Vendor Manager',
  'Supplier Quality Engineer',
  'Import/Export Manager',
  'Customs Compliance Specialist',
  'Trade Compliance Manager',
  'Shipping Coordinator',
  'Receiving Clerk',
  'Freight Coordinator',
  'Dispatcher',
  'Route Planner',
  'Last Mile Delivery Manager',
  'Operations Analyst',
  'Process Improvement Manager',
  'Continuous Improvement Manager',
  'Lean Six Sigma Black Belt',
  'Lean Six Sigma Green Belt',
  'Quality Manager',
  'Quality Assurance Manager',
  'Quality Control Inspector',
  'Health & Safety Manager',
  'Safety Officer',
  'Environmental Health & Safety (EHS) Manager',
  'Risk Manager (Operations)',
  'Business Continuity Manager',

  // ========== PROJECT MANAGEMENT ==========
  'Project Management Office (PMO) Director',
  'PMO Manager',
  'Program Manager',
  'Senior Project Manager',
  'Project Manager',
  'Junior Project Manager',
  'Project Coordinator',
  'Project Administrator',
  'Project Scheduler',
  'Project Controller',
  'Technical Project Manager',
  'IT Project Manager',
  'Construction Project Manager',
  'Engineering Project Manager',
  'Marketing Project Manager',
  'Event Project Manager',
  'Creative Project Manager',
  'Agile Coach',
  'Scrum Master',
  'Product Owner',
  'Release Manager',
  'Delivery Manager',
  'Implementation Manager',
  'Change Manager',
  'Transformation Manager',

  // ========== ADMINISTRATIVE & OFFICE SUPPORT ==========
  'Office Manager',
  'Administrative Manager',
  'Executive Assistant',
  'Personal Assistant',
  'Administrative Assistant',
  'Administrative Coordinator',
  'Administrative Specialist',
  'Office Coordinator',
  'Office Assistant',
  'Receptionist',
  'Front Desk Coordinator',
  'Data Entry Clerk',
  'Clerk',
  'File Clerk',
  'Records Manager',
  'Document Controller',
  'Secretary',
  'Executive Secretary',
  'Virtual Assistant',
  'Scheduler',
  'Appointment Setter',
  'Mailroom Clerk',
  'Courier',
  'Office Clerk',
  'General Office Assistant',

  // ========== LEGAL ==========
  'General Counsel',
  'Legal Director',
  'Senior Counsel',
  'Corporate Counsel',
  'In-House Counsel',
  'Attorney',
  'Lawyer',
  'Partner (Law Firm)',
  'Associate (Law Firm)',
  'Of Counsel',
  'Paralegal',
  'Legal Assistant',
  'Legal Secretary',
  'Legal Clerk',
  'Litigation Specialist',
  'Corporate Lawyer',
  'M&A Lawyer',
  'Intellectual Property Lawyer',
  'Patent Attorney',
  'Trademark Attorney',
  'Tax Attorney',
  'Real Estate Attorney',
  'Employment Lawyer',
  'Immigration Lawyer',
  'Criminal Defense Lawyer',
  'Family Lawyer',
  'Estate Planning Lawyer',
  'Bankruptcy Lawyer',
  'Contract Manager',
  'Contracts Specialist',
  'Legal Operations Manager',
  'Compliance Officer',
  'Compliance Manager',
  'Regulatory Affairs Manager',
  'Regulatory Specialist',
  'Court Clerk',
  'Judge',
  'Magistrate',
  'Mediator',
  'Arbitrator',
  'Legal Consultant',

  // ========== HEALTHCARE & MEDICAL ==========
  // Physicians
  'Chief Medical Officer',
  'Medical Director',
  'Physician',
  'Doctor',
  'Primary Care Physician',
  'Family Medicine Physician',
  'Internal Medicine Physician',
  'Pediatrician',
  'Geriatrician',
  'Cardiologist',
  'Dermatologist',
  'Gastroenterologist',
  'Neurologist',
  'Oncologist',
  'Ophthalmologist',
  'Orthopedic Surgeon',
  'ENT Specialist',
  'Urologist',
  'Gynecologist',
  'Obstetrician',
  'Psychiatrist',
  'Radiologist',
  'Anesthesiologist',
  'Emergency Medicine Physician',
  'Surgeon',
  'Neurosurgeon',
  'Plastic Surgeon',
  'Pathologist',
  'Hospitalist',

  // Nursing
  'Chief Nursing Officer',
  'Nursing Director',
  'Nurse Manager',
  'Nurse Supervisor',
  'Registered Nurse (RN)',
  'Licensed Practical Nurse (LPN)',
  'Nurse Practitioner (NP)',
  'Clinical Nurse Specialist',
  'Certified Nurse Midwife',
  'Certified Registered Nurse Anesthetist',
  'Emergency Room Nurse',
  'ICU Nurse',
  'Operating Room Nurse',
  'Pediatric Nurse',
  'Oncology Nurse',
  'Home Health Nurse',
  'School Nurse',
  'Occupational Health Nurse',

  // Allied Health
  'Physician Assistant',
  'Pharmacist',
  'Pharmacy Technician',
  'Dentist',
  'Dental Hygienist',
  'Dental Assistant',
  'Physical Therapist',
  'Physical Therapy Assistant',
  'Occupational Therapist',
  'Speech-Language Pathologist',
  'Audiologist',
  'Respiratory Therapist',
  'Radiologic Technologist',
  'MRI Technologist',
  'Ultrasound Technologist',
  'Nuclear Medicine Technologist',
  'Medical Laboratory Scientist',
  'Medical Lab Technician',
  'Phlebotomist',
  'EMT',
  'Paramedic',
  'Dietitian',
  'Nutritionist',
  'Chiropractor',
  'Optometrist',
  'Optician',
  'Podiatrist',
  'Psychologist',
  'Counselor',
  'Therapist',
  'Social Worker',
  'Clinical Social Worker',

  // Healthcare Administration
  'Hospital Administrator',
  'Clinic Manager',
  'Practice Manager',
  'Healthcare Administrator',
  'Medical Practice Administrator',
  'Health Information Manager',
  'Medical Records Manager',
  'Patient Access Manager',
  'Admissions Coordinator',
  'Patient Coordinator',
  'Medical Secretary',
  'Medical Receptionist',
  'Billing Specialist (Medical)',
  'Medical Coder',
  'Medical Biller',
  'Revenue Cycle Manager',
  'Clinical Research Coordinator',
  'Clinical Trial Manager',
  'Healthcare Consultant',

  // ========== EDUCATION & ACADEMIA ==========
  // Administration
  'Superintendent',
  'Principal',
  'Vice Principal',
  'Assistant Principal',
  'Dean',
  'Dean of Students',
  'Dean of Faculty',
  'Academic Dean',
  'Department Chair',
  'Head of School',
  'Chancellor',
  'Provost',
  'University President',
  'College President',
  'Campus Director',
  'Registrar',
  'Admissions Director',
  'Director of Enrollment',
  'Financial Aid Director',

  // Faculty
  'Professor',
  'Distinguished Professor',
  'Emeritus Professor',
  'Associate Professor',
  'Assistant Professor',
  'Adjunct Professor',
  'Visiting Professor',
  'Lecturer',
  'Senior Lecturer',
  'Instructor',
  'Teaching Assistant',
  'Graduate Teaching Assistant',
  'Fellow',
  'Postdoctoral Fellow',
  'Research Fellow',
  'Research Associate',
  'Research Assistant',
  'Professor of Practice',

  // K-12
  'Teacher',
  'Classroom Teacher',
  'Elementary Teacher',
  'Middle School Teacher',
  'High School Teacher',
  'Subject Teacher',
  'Math Teacher',
  'Science Teacher',
  'English Teacher',
  'History Teacher',
  'Art Teacher',
  'Music Teacher',
  'Physical Education Teacher',
  'Special Education Teacher',
  'ESL Teacher',
  'Foreign Language Teacher',
  'Substitute Teacher',
  'Teacher Aide',
  'Paraprofessional',
  'Teaching Assistant',
  'Instructional Assistant',
  'Guidance Counselor',
  'School Counselor',
  'School Psychologist',
  'Librarian',
  'Media Specialist',

  // Early Childhood
  'Preschool Director',
  'Preschool Teacher',
  'Daycare Director',
  'Childcare Provider',
  'Early Childhood Educator',
  'Nursery Teacher',
  'Kindergarten Teacher',
  'Toddler Teacher',
  'Infant Teacher',

  // Higher Education Support
  'Academic Advisor',
  'Student Advisor',
  'Career Counselor',
  'Resident Director',
  'Residence Life Coordinator',
  'Student Activities Coordinator',
  'Orientation Leader',
  'Study Abroad Coordinator',
  'Alumni Relations Manager',
  'Development Officer',
  'Grant Writer',
  'Research Administrator',
  'Lab Manager',
  'Lab Technician',

  // ========== HOSPITALITY & TOURISM ==========
  'Hotel Manager',
  'General Manager (Hotel)',
  'Assistant Hotel Manager',
  'Front Office Manager',
  'Guest Relations Manager',
  'Housekeeping Manager',
  'Executive Housekeeper',
  'Food & Beverage Manager',
  'Restaurant Manager',
  'Assistant Restaurant Manager',
  'Banquet Manager',
  'Catering Manager',
  'Conference Services Manager',
  'Event Manager',
  'Wedding Coordinator',
  'Reservations Manager',
  'Revenue Manager (Hotel)',
  'Spa Manager',
  'Recreation Manager',
  'Concierge',
  'Front Desk Agent',
  'Guest Service Agent',
  'Bellhop',
  'Porter',
  'Valet',
  'Room Attendant',
  'Housekeeper',
  'Chef',
  'Executive Chef',
  'Sous Chef',
  'Line Cook',
  'Prep Cook',
  'Pastry Chef',
  'Kitchen Manager',
  'Dishwasher',
  'Server',
  'Waiter',
  'Waitress',
  'Bartender',
  'Barista',
  'Host/Hostess',
  'Busser',
  'Sommelier',
  'Restaurant Host',
  'Fast Food Crew',
  'Travel Agent',
  'Tour Operator',
  'Tour Guide',
  'Travel Consultant',
  'Cruise Director',
  'Flight Attendant',
  'Pilot',
  'Airline Pilot',
  'Co-pilot',
  'Flight Engineer',
  'Cabin Crew',
  'Travel Writer',
  'Resort Manager',
  'Activities Coordinator',

  // ========== RETAIL & CONSUMER GOODS ==========
  'Retail Store Manager',
  'Assistant Store Manager',
  'Department Manager',
  'Shift Manager',
  'Team Leader',
  'Sales Associate',
  'Cashier',
  'Stock Clerk',
  'Inventory Clerk',
  'Visual Merchandiser',
  'Visual Manager',
  'Buyer',
  'Assistant Buyer',
  'Planner',
  'Allocator',
  'District Manager',
  'Regional Manager',
  'Area Manager',
  'Store Planner',
  'Loss Prevention Manager',
  'Loss Prevention Officer',
  'Security Guard',
  'E-commerce Manager',
  'Online Store Manager',
  'Marketplace Manager',
  'Category Manager',
  'Merchandise Manager',
  'Product Manager (Retail)',
  'Retail Buyer',
  'Fashion Buyer',
  'Fashion Merchandiser',
  'Personal Shopper',
  'Stylist',
  'Brand Representative',
  'Pop-up Store Manager',
  'Concession Manager',
  'Retail Operations Manager',

  // ========== MANUFACTURING & INDUSTRIAL ==========
  'Plant Manager',
  'Factory Manager',
  'Production Manager',
  'Shift Supervisor',
  'Production Supervisor',
  'Line Leader',
  'Team Lead (Manufacturing)',
  'Machine Operator',
  'CNC Operator',
  'Forklift Operator',
  'Assembly Line Worker',
  'Assembler',
  'Fabricator',
  'Welder',
  'Machinist',
  'Toolmaker',
  'Die Maker',
  'Maintenance Technician',
  'Maintenance Manager',
  'Facilities Engineer',
  'Industrial Engineer',
  'Manufacturing Engineer',
  'Process Engineer',
  'Quality Engineer',
  'Quality Control Inspector',
  'Test Technician',
  'Product Engineer',
  'Design Engineer',
  'CAD Designer',
  'Drafter',
  'Production Planner',
  'Scheduler',
  'Inventory Analyst',
  'Materials Manager',
  'Supply Chain Coordinator',
  'Lean Manufacturing Specialist',
  'Continuous Improvement Manager',
  'Six Sigma Black Belt',
  'Safety Manager',
  'Environmental Health & Safety Specialist',
  'Industrial Hygienist',

  // ========== CONSTRUCTION & TRADES ==========
  'Construction Manager',
  'Project Manager (Construction)',
  'Site Manager',
  'Site Supervisor',
  'General Foreman',
  'Foreman',
  'Crew Leader',
  'Construction Superintendent',
  'Project Engineer (Construction)',
  'Field Engineer',
  'Estimator',
  'Quantity Surveyor',
  'Bid Coordinator',
  'Scheduler (Construction)',
  'Safety Manager (Construction)',
  'Safety Officer',
  'Carpenter',
  'Electrician',
  'Plumber',
  'Pipefitter',
  'HVAC Technician',
  'Mason',
  'Bricklayer',
  'Concrete Finisher',
  'Drywall Installer',
  'Painter',
  'Roofer',
  'Siding Installer',
  'Flooring Installer',
  'Tile Setter',
  'Cabinet Maker',
  'Millwright',
  'Ironworker',
  'Welder (Construction)',
  'Equipment Operator',
  'Heavy Equipment Operator',
  'Crane Operator',
  'Forklift Operator (Construction)',
  'Laborer',
  'Construction Worker',
  'Apprentice',
  'Journeyman',
  'Master Craftsman',
  'Building Inspector',
  'Code Enforcement Officer',
  'Home Inspector',
  'Architect',
  'Landscape Architect',
  'Interior Designer',
  'Urban Planner',
  'Civil Engineer',
  'Structural Engineer',
  'Surveyor',
  'Land Surveyor',

  // ========== TRANSPORTATION & LOGISTICS ==========
  'Truck Driver',
  'Delivery Driver',
  'Courier',
  'Parcel Delivery Driver',
  'Bus Driver',
  'Coach Driver',
  'Taxi Driver',
  'Rideshare Driver',
  'Chauffeur',
  'Train Conductor',
  'Locomotive Engineer',
  'Subway Operator',
  'Tram Driver',
  'Ship Captain',
  'Boat Captain',
  'Sailor',
  'Deckhand',
  'Longshoreman',
  'Dock Worker',
  'Warehouse Worker',
  'Picker',
  'Packer',
  'Forklift Operator',
  'Reach Truck Operator',
  'Order Selector',
  'Loader',
  'Unloader',
  'Shipper',
  'Receiver',
  'Logistics Coordinator',
  'Transportation Coordinator',
  'Fleet Manager',
  'Dispatch Manager',
  'Dispatcher',
  'Route Planner',
  'Driver Manager',
  'Safety Supervisor',
  'Logistics Analyst',
  'Supply Chain Analyst',
  'Import/Export Coordinator',
  'Customs Broker',
  'Freight Forwarder',
  'Air Cargo Agent',
  'Railroad Clerk',

  // ========== ARTS, MEDIA & ENTERTAINMENT ==========
  // Visual Arts
  'Artist',
  'Painter',
  'Sculptor',
  'Illustrator',
  'Graphic Artist',
  'Concept Artist',
  'Storyboard Artist',
  'Animator',
  '3D Artist',
  'VFX Artist',
  'Game Artist',

  // Performing Arts
  'Actor',
  'Actress',
  'Performer',
  'Dancer',
  'Choreographer',
  'Singer',
  'Musician',
  'Composer',
  'Conductor',
  'Orchestra Member',
  'Band Member',
  'DJ',

  // Film & TV
  'Director',
  'Film Director',
  'Assistant Director',
  'Producer',
  'Film Producer',
  'Executive Producer',
  'Cinematographer',
  'Director of Photography',
  'Camera Operator',
  'Sound Engineer',
  'Sound Mixer',
  'Boom Operator',
  'Gaffer',
  'Lighting Technician',
  'Grip',
  'Key Grip',
  'Production Assistant',
  'PA',
  'Script Supervisor',
  'Screenwriter',
  'Writer',
  'Editor',
  'Film Editor',
  'Video Editor',
  'Colorist',
  'Post-production Supervisor',
  'Casting Director',
  'Casting Associate',
  'Location Manager',
  'Set Designer',
  'Prop Master',
  'Costume Designer',
  'Makeup Artist',
  'Hair Stylist',

  // Media & Journalism
  'Journalist',
  'Reporter',
  'News Reporter',
  'Correspondent',
  'Anchor',
  'News Anchor',
  'Weather Reporter',
  'Sports Reporter',
  'Investigative Journalist',
  'Photojournalist',
  'Editor (Media)',
  'News Editor',
  'Copy Editor',
  'Managing Editor',
  'Editor-in-Chief',
  'Publisher',
  'Columnist',
  'Blogger',
  'Content Creator',
  'Influencer',
  'Social Media Influencer',
  'YouTuber',
  'Streamer',
  'Podcaster',
  'Radio Host',
  'Radio DJ',
  'Broadcaster',

  // Publishing
  'Author',
  'Writer (Book)',
  'Novelist',
  'Ghostwriter',
  'Editor (Book)',
  'Acquisitions Editor',
  'Developmental Editor',
  'Proofreader',
  'Literary Agent',
  'Book Publicist',

  // Music Industry
  'Recording Artist',
  'Session Musician',
  'Studio Musician',
  'Music Producer',
  'Record Producer',
  'Audio Engineer',
  'Mixing Engineer',
  'Mastering Engineer',
  'A&R Representative',
  'Artist Manager',
  'Music Publisher',
  'Music Supervisor',
  'Booking Agent',
  'Concert Promoter',
  'Tour Manager',
  'Roadie',

  // Events & Entertainment
  'Event Planner',
  'Event Coordinator',
  'Wedding Planner',
  'Conference Organizer',
  'Exhibition Organizer',
  'Trade Show Manager',
  'Festival Director',
  'Concert Manager',
  'Venue Manager',
  'Stage Manager',
  'Production Manager (Events)',
  'Technical Director (Events)',
  'Sound Tech',
  'Lighting Tech',
  'Rigger',
  'Museum Curator',
  'Gallery Manager',
  'Art Dealer',
  'Art Handler',
  'Framer',

  // ========== SPORTS & FITNESS ==========
  // Athletes
  'Professional Athlete',
  'Player',
  'Competitor',

  // Coaching
  'Head Coach',
  'Assistant Coach',
  'Position Coach',
  'Strength & Conditioning Coach',
  'Fitness Coach',
  'Technical Coach',
  'Performance Coach',
  'Youth Coach',

  // Sports Management
  'General Manager (Sports)',
  'Sports Director',
  'Athletic Director',
  'Team Manager',
  'Sports Administrator',
  'Scout',
  'Talent Scout',
  'Sports Agent',
  'Player Agent',
  'Contract Negotiator',

  // Officiating
  'Referee',
  'Umpire',
  'Official',
  'Linesman',
  'Judge (Sports)',
  'Timekeeper',
  'Scorekeeper',

  // Fitness
  'Personal Trainer',
  'Fitness Instructor',
  'Group Fitness Instructor',
  'Yoga Instructor',
  'Pilates Instructor',
  'Spin Instructor',
  'CrossFit Coach',
  'Gym Manager',
  'Fitness Center Manager',
  'Health Club Manager',
  'Wellness Coach',
  'Nutrition Coach',

  // Sports Science
  'Sports Scientist',
  'Exercise Physiologist',
  'Biomechanist',
  'Sports Psychologist',
  'Nutritionist (Sports)',
  'Physical Therapist (Sports)',
  'Athletic Trainer',
  'Sports Medicine Doctor',

  // Sports Media
  'Sports Broadcaster',
  'Sports Commentator',
  'Sports Analyst',
  'Sports Writer',
  'Sports Columnist',
  'Sports Blogger',
  'Sports Photographer',

  // ========== SCIENCE & RESEARCH ==========
  // Life Sciences
  'Research Scientist',
  'Principal Investigator',
  'Lab Director',
  'Laboratory Manager',
  'Research Associate',
  'Research Assistant',
  'Lab Technician',
  'Biologist',
  'Molecular Biologist',
  'Cell Biologist',
  'Microbiologist',
  'Geneticist',
  'Biochemist',
  'Biophysicist',
  'Neuroscientist',
  'Ecologist',
  'Marine Biologist',
  'Zoologist',
  'Botanist',
  'Forensic Scientist',
  'Toxicologist',
  'Pharmacologist',

  // Physical Sciences
  'Physicist',
  'Astrophysicist',
  'Astronomer',
  'Chemist',
  'Analytical Chemist',
  'Organic Chemist',
  'Inorganic Chemist',
  'Physical Chemist',
  'Materials Scientist',
  'Geologist',
  'Geophysicist',
  'Geochemist',
  'Paleontologist',
  'Meteorologist',
  'Climatologist',
  'Oceanographer',
  'Environmental Scientist',
  'Soil Scientist',

  // Mathematics & Statistics
  'Mathematician',
  'Statistician',
  'Biostatistician',
  'Epidemiologist',
  'Data Scientist',
  'Quantitative Analyst',
  'Operations Research Analyst',

  // Research Support
  'Research Coordinator',
  'Clinical Research Coordinator',
  'Research Nurse',
  'Research Ethics Coordinator',
  'IRB Coordinator',
  'Grant Writer',
  'Scientific Writer',
  'Technical Writer (Science)',
  'Science Communicator',
  'Science Journalist',
  'Science Editor',
  'Lab Safety Officer',
  'Animal Care Technician',
  'Vivarium Manager',

  // ========== SOCIAL SERVICES & NONPROFIT ==========
  // Direct Service
  'Social Worker',
  'Clinical Social Worker',
  'Case Manager',
  'Caseworker',
  'Counselor',
  'Therapist',
  'Marriage & Family Therapist',
  'Mental Health Counselor',
  'Substance Abuse Counselor',
  'Addiction Counselor',
  'Crisis Counselor',
  'Hotline Operator',
  'Crisis Intervention Specialist',
  'Youth Worker',
  'Outreach Worker',
  'Community Health Worker',
  'Home Health Aide',
  'Personal Care Aide',
  'Hospice Worker',
  'Palliative Care Specialist',

  // Nonprofit Management
  'Executive Director (Nonprofit)',
  'Nonprofit Director',
  'Program Director',
  'Program Manager',
  'Program Coordinator',
  'Project Coordinator (Nonprofit)',
  'Volunteer Coordinator',
  'Volunteer Manager',
  'Development Director',
  'Fundraising Manager',
  'Major Gifts Officer',
  'Planned Giving Officer',
  'Grant Writer',
  'Grant Manager',
  'Foundation Relations Manager',
  'Corporate Partnerships Manager',
  'Donor Relations Manager',
  'Stewardship Coordinator',
  'Membership Coordinator',
  'Annual Fund Manager',
  'Communications Director (Nonprofit)',
  'Advocacy Director',
  'Policy Director',
  'Policy Analyst',
  'Community Organizer',
  'Advocate',
  'Humanitarian Worker',
  'Relief Worker',
  'Aid Worker',
  'International Development Specialist',
  'Peace Corps Volunteer',

  // Religious & Spiritual
  'Clergy',
  'Priest',
  'Pastor',
  'Minister',
  'Reverend',
  'Chaplain',
  'Rabbi',
  'Imam',
  'Monk',
  'Nun',
  'Missionary',
  'Religious Educator',
  'Youth Minister',
  'Worship Leader',
  'Music Minister',
  'Church Administrator',

  // ========== GOVERNMENT & PUBLIC SERVICE ==========
  // Elected Officials
  'President',
  'Vice President',
  'Governor',
  'Lieutenant Governor',
  'Mayor',
  'City Council Member',
  'Councilperson',
  'Alderman',
  'County Commissioner',
  'Senator',
  'State Senator',
  'US Senator',
  'Representative',
  'State Representative',
  'Congressperson',
  'Member of Congress',
  'MP (Member of Parliament)',
  'Prime Minister',
  'Chancellor',
  'Cabinet Member',
  'Secretary (Government)',
  'Minister (Government)',
  'Ambassador',
  'Diplomat',
  'Consul',
  'Judge',
  'Magistrate',
  'Justice',
  'Supreme Court Justice',
  'Attorney General',
  'District Attorney',
  'Prosecutor',
  'Public Defender',

  // Civil Service
  'City Manager',
  'Town Administrator',
  'County Administrator',
  'City Clerk',
  'Town Clerk',
  'Municipal Clerk',
  'City Planner',
  'Urban Planner',
  'Zoning Administrator',
  'Building Inspector',
  'Code Enforcement Officer',
  'Public Works Director',
  'Parks & Recreation Director',
  'Librarian (Public)',
  'Fire Chief',
  'Firefighter',
  'Police Chief',
  'Police Officer',
  'Sheriff',
  'Deputy Sheriff',
  'State Trooper',
  'Correctional Officer',
  'Prison Warden',
  'Probation Officer',
  'Parole Officer',
  'Court Clerk',
  'Bailiff',
  'Emergency Manager',
  'FEMA Coordinator',
  'Public Health Officer',
  'Health Inspector',
  'Sanitation Worker',
  'Waste Management Operator',
  'Transit Authority Manager',
  'Bus Operator (Public)',
  'Train Operator (Public)',

  // Policy & Administration
  'Policy Advisor',
  'Policy Analyst',
  'Legislative Aide',
  'Congressional Aide',
  'Staff Assistant',
  'Chief of Staff',
  'Press Secretary',
  'Communications Director (Government)',
  'Public Information Officer',
  'Government Relations Manager',
  'Lobbyist',
  'Regulatory Affairs Specialist',
  'Budget Analyst (Government)',
  'Government Accountant',
  'Tax Examiner',
  'Revenue Agent',
  'Customs Officer',
  'Immigration Officer',
  'Border Patrol Agent',
  'TSA Agent',
  'FBI Agent',
  'CIA Officer',
  'Intelligence Analyst',
  'Foreign Service Officer',

  // Military
  'General',
  'Admiral'
]
export const skills_and_tools = [
  // ========== TECHNICAL CORE ==========
  // Development
  'Frontend Development',
  'Backend Development',
  'Full Stack',
  'Mobile Development',
  'Desktop Applications',
  'Embedded Systems',
  'API Design & Development',
  'Microservices Architecture',
  'Legacy System Maintenance',
  'Technical Debt Management',

  // Frontend Technologies
  'HTML5',
  'CSS3',
  'JavaScript (ES6+)',
  'TypeScript',
  'React.js',
  'Next.js',
  'Vue.js',
  'Angular',
  'Redux',
  'Redux Toolkit',
  'Zustand',
  'Context API',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'SASS/SCSS',

  // Backend Technologies
  'Node.js',
  'Express.js',
  'Python',
  'Django',
  'Flask',
  'Java',
  'Spring Boot',
  'C#',
  'ASP.NET Core',
  'PHP',
  'Laravel',
  'Go',
  'Rust',
  'RESTful APIs',
  'GraphQL',
  'WebSockets',
  'Microservices',

  // Databases
  'PostgreSQL',
  'MySQL',
  'SQLite',
  'Microsoft SQL Server',
  'MongoDB',
  'Firebase Firestore',
  'Redis',
  'Cassandra',
  'Elasticsearch',
  'DynamoDB',
  'CouchDB',
  'Prisma',
  'Sequelize',
  'Mongoose',
  'TypeORM',
  'Drizzle',

  // DevOps & Cloud
  'Docker',
  'Kubernetes',
  'Jenkins',
  'GitHub Actions',
  'AWS (EC2, S3, Lambda, RDS)',
  'Google Cloud Platform',
  'Microsoft Azure',
  'Heroku',
  'Netlify',
  'Vercel',
  'Terraform',
  'Ansible',
  'Prometheus',
  'Grafana',

  // Version Control & Tools
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'Git Flow',
  'Trunk-based Development',
  'Jira',
  'Trello',
  'Asana',
  'Confluence',
  'Slack',
  'Microsoft Teams',
  'Discord',

  // Testing
  'Jest',
  'Mocha',
  'Chai',
  'Jasmine',
  'React Testing Library',
  'Vitest',
  'Cypress',
  'Playwright',
  'Selenium',
  'Puppeteer',
  'Postman',
  'Insomnia',
  'REST Assured',
  'Lighthouse',
  'WebPageTest',
  'k6',

  // Mobile Development
  'React Native',
  'Flutter',
  'Swift (iOS)',
  'Kotlin (Android)',
  'Ionic',
  'Xamarin',
  'Expo',
  'Firebase for Mobile',

  // Programming Languages
  'JavaScript/TypeScript',
  'Python',
  'Java',
  'C++',
  'C#',
  'Go',
  'Rust',
  'PHP',
  'Ruby',
  'Swift',
  'Kotlin',
  'Dart',
  'Shell Scripting',

  // Development Tools
  'VS Code',
  'WebStorm',
  'IntelliJ IDEA',
  'PyCharm',
  'Sublime Text',
  'Vim/Neovim',
  'npm',
  'yarn',
  'pnpm',
  'pip',
  'maven',
  'gradle',
  'Chrome DevTools',
  'React DevTools',
  'Redux DevTools',
  'Postman',
  'Swagger',
  'OpenAPI',
  'GraphQL Playground',
  'Figma',
  'Adobe XD',
  'Sketch',

  // Specialized Technical
  'Web Security',
  'Authentication (JWT, OAuth)',
  'HTTPS/SSL',
  'Security Best Practices',
  'OWASP Top 10',
  'Web Performance Optimization',
  'Code Splitting',
  'Lazy Loading',
  'Caching Strategies',
  'CDN Configuration',
  'System Design',
  'Scalability',
  'Load Balancing',
  'Database Sharding',
  'Message Queues (RabbitMQ, Kafka)',
  'SEO Fundamentals',
  'Semantic HTML',
  'Meta Tags',
  'Structured Data',
  'Core Web Vitals',

  // ========== BUSINESS & STRATEGY ==========
  'Business Acumen',
  'Market Research',
  'Competitive Analysis',
  'Product-Market Fit',
  'Go-to-Market Strategy',
  'ROI Analysis',
  'Cost-Benefit Analysis',
  'Risk Assessment',
  'Business Modeling',
  'Value Proposition Design',
  'Customer Discovery',
  'User Research',
  'Feature Prioritization',
  'MVP Planning',
  'Product Roadmapping',
  'Technical Product Management',
  'Industry Domain Expertise',
  'Regulatory Compliance',
  'Data Privacy (GDPR/CCPA)',
  'Accessibility Standards (WCAG)',
  'Security Compliance',
  'Financial Modeling',

  // ========== PROJECT MANAGEMENT ==========
  'Agile/Scrum',
  'Kanban',
  'Waterfall',
  'Hybrid Approaches',
  'SAFe (Scaled Agile)',
  'Lean Methodology',
  'Extreme Programming',
  'Sprint Planning',
  'Story Point Estimation',
  'Velocity Tracking',
  'Burndown Charts',
  'Release Management',
  'Deployment Strategies',
  'Blue-Green Deployment',
  'Canary Releases',
  'Feature Flags',
  'Technical Documentation',
  'API Documentation',
  'User Manuals',
  'System Architecture Diagrams',
  'ER Diagrams',
  'Flowcharts',
  'Architecture Decision Records',

  // ========== LEADERSHIP & MANAGEMENT ==========
  'Team Building',
  'Talent Development',
  'Mentoring',
  'Coaching',
  'Performance Reviews',
  'Career Pathing',
  'Succession Planning',
  'Conflict Resolution',
  'Difficult Conversations',
  'Technical Vision',
  'Architecture Decisions',
  'Tech Stack Selection',
  'Code Standards Enforcement',
  'Best Practices Definition',
  'Innovation Encouragement',
  'Technical Debt Prioritization',
  'Cross-functional Collaboration',
  'Stakeholder Management',
  'Executive Communication',
  'Board Presentations',
  'Budget Planning',
  'Resource Allocation',
  'Vendor Management',

  // ========== COMMUNICATION ==========
  'Technical Writing',
  'Business Writing',
  'Email Etiquette',
  'Proposal Writing',
  'RFP Responses',
  'Status Reports',
  'Post-mortems',
  'Incident Reports',
  'Meeting Minutes',
  'Presentations',
  'Public Speaking',
  'Pitching Ideas',
  'Requirements Gathering',
  'Client Meetings',
  'Negotiation',
  'Facilitation',
  'Workshop Leading',
  'Training Delivery',
  'Data Visualization',
  'Dashboard Design',
  'Infographics',
  'Wireframing',
  'Prototyping',
  'Mockups',
  'Active Listening',
  'Empathy',
  'Emotional Intelligence',
  'Persuasion',
  'Storytelling',
  'Networking',

  // ========== PROBLEM SOLVING ==========
  'Root Cause Analysis',
  '5 Whys Technique',
  'Fishbone Diagrams',
  'First Principles Thinking',
  'Systems Thinking',
  'Design Thinking',
  'Lateral Thinking',
  'Critical Thinking',
  'Decision Trees',
  'Bottleneck Identification',
  'Trade-off Analysis',
  'Creative Problem Solving',
  'Brainstorming Facilitation',

  // ========== OPERATIONS ==========
  'Incident Management',
  'On-call Rotation',
  'SLA Management',
  'Capacity Planning',
  'Cost Optimization',
  'Vendor Negotiation',
  'Asset Management',
  'License Compliance',
  'Process Automation',
  'Workflow Optimization',
  'Bottleneck Removal',
  'Cycle Time Reduction',
  'Quality Assurance',
  'Continuous Improvement',
  'Kaizen',
  'Six Sigma',
  'Lean Principles',
  'Customer Support',
  'Technical Troubleshooting',
  'Escalation Management',
  'Knowledge Base Creation',
  'Self-service Tools',

  // ========== QUALITY & STANDARDS ==========
  'Code Reviews',
  'Pair Programming',
  'Static Analysis',
  'Linting Standards',
  'Style Guides',
  'Refactoring',
  'Test Planning',
  'Test Automation Strategy',
  'Coverage Analysis',
  'Shift-left Testing',
  'Integration Testing',
  'E2E Testing',
  'Coding Standards',
  'Accessibility (a11y)',
  'Internationalization (i18n)',
  'Performance Budgets',
  'Security Audits',
  'Penetration Testing',

  // ========== PEOPLE & CULTURE ==========
  'Technical Interviewing',
  'Resume Screening',
  'Take-home Assignments',
  'Onboarding Programs',
  'Internship Mentoring',
  'Culture Building',
  'Psychological Safety',
  'Diversity & Inclusion',
  'Remote Work Best Practices',
  'Team Morale',
  'Recognition Programs',
  'Retention Strategies',
  'Exit Interviews',
  'Cross-team Collaboration',
  'Knowledge Sharing',
  'Communities of Practice',
  'Guilds/Chapters',
  'Internal Open Source',
  'Hackathons',

  // ========== COMMERCIAL ==========
  'Budgeting',
  'Cost Estimation',
  'Time Tracking',
  'Billing',
  'Profit & Loss (P&L)',
  'Revenue Models',
  'Pricing Strategy',
  'License Models',
  'Sales Engineering',
  'Client Consulting',
  'Statement of Work (SoW)',
  'Contract Negotiation',
  'Renewal Management',
  'Upselling',
  'Partnership Development',
  'Ecosystem Building',
  'OKRs',
  'KPIs',
  'North Star Metrics',
  'CAC',
  'LTV',
  'MRR',
  'Churn Rate',

  // ========== INNOVATION ==========
  'Research & Development',
  'Proof of Concept',
  'Rapid Prototyping',
  'Experimentation',
  'A/B Testing',
  'Emerging Technology Evaluation',
  'Trend Analysis',
  'Patent Writing',
  'Intellectual Property',
  'Open Source Contribution',
  'Conference Speaking',
  'Workshop Creation',
  'Technical Blogging',
  'Continuous Learning',
  'Certification Pursuit',

  // ========== SOFT SKILLS ==========
  'Adaptability',
  'Resilience',
  'Self-motivation',
  'Time Management',
  'Work-life Balance',
  'Stress Management',
  'Mindfulness',
  'Collaboration',
  'Teamwork',
  'Relationship Building',
  'Conflict Management',
  'Giving Feedback',
  'Receiving Feedback',
  'Appreciation',
  'Trust Building',
  'Professionalism',
  'Reliability',
  'Accountability',
  'Initiative',
  'Ownership Mindset',
  'Proactiveness',
  'Follow-through',
  'Attention to Detail',
  'Big Picture Thinking',

  // ========== ROLE-SPECIFIC ==========
  'Clean Code',
  'Debugging',
  'Performance Optimization',
  'Technical Decision Making',
  'Code Review Culture',
  'Estimation Accuracy',
  'Risk Mitigation',
  '1:1 Meetings',
  'Team Health',
  'Hiring Funnel',
  'User Stories',
  'Backlog Grooming',
  'User Testing',
  'Analytics',
  'Feature Success Metrics',
  'System Integration',
  'Scalability Planning',
  'Security Architecture',
  'Technical Sales Support',
  'RFI/RFP Response',
  'Proof of Value',
  'Client Relationship',
  'Expectation Management',
  'Deliverable Definition',
  'Scope Control',
  'Change Management',
  'Business Value Articulation',

  // ========== SCENARIO SKILLS ==========
  'Requirements Analysis',
  'Technical Design',
  'Task Breakdown',
  'Implementation',
  'Code Review Participation',
  'Deployment',
  'Post-launch Monitoring',
  'User Feedback Collection',
  'Incident Diagnosis',
  'Impact Assessment',
  'Mitigation Steps',
  'Status Updates',
  'Post-mortem Facilitation',
  'Preventive Measures',
  'Agenda Setting',
  'Business Context Understanding',
  'Technical Explanation (Non-technical)',
  'Handling Objections',
  'Candidate Experience',
  'Unbiased Evaluation',
  'Feedback Consolidation'
]
